### ISSUE TITLE
allow specifying pars for inclusion in `equi_test` etc.

### ISSUE THREAD

**Issue by rubenarslan** [sjPlot/sjstats#72] opened 2019-03-13 08:11 UTC
I fit an errors-in-variables model in brms (i.e., with the term `me(age, age_se)`) and `sjstats` parameter extraction misfired (it shows a bunch of parameters in `tab_model` and `equi_test` that are not shown when calling `summary.brmsfit`. It would be cool, if you permitted a `pars` argument like many brms and bayesplot functions to allow customisation.

This would not just be useful for misfiring like above, but also to trim the tested parameters in `equi_test` if not all are of substantial interest.

**Comment by strengejacke** [comment] 2019-03-13 08:23
Do you have a reproducible example? I know what you're meaning, but I would like to see the output, because this issue might be related to https://github.com/easystats/insight/issues/55.

Furthermore, I would close this issue in favor of https://github.com/easystats/bayestestR/issues/37

The bayestestR-package will comprise all the relevant Bayes-stuff, and functions in sjstats that are covered by the bayestestR package will be deprecated and defunct in the future.

**Closed as completed by strengejacke** 2019-03-13 08:23 UTC
